apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}

            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
